hub_server: 'hub'
staffchat_format: '&e&l[STAFF] &r&9{player}&r: {message}'
hide_plugins: true
join_message_enabled: false
quit_message_enabled: false
kick_on_high_ping: false
ping_kick_threshold: 150