name: PafiasEssentials
version: ${project.version}
main: me.pafias.pafiasessentials.PafiasEssentials
softdepend: [ ProtocolLib, PlaceholderAPI ]
author: Pafias
description: PafiasEssentials
api-version: 1.13
commands:
  entity:
    aliases: [ e ]
  sound:
    aliases: [ snd ]
  nightvision:
    aliases: [ nv ]
  ping:
    aliases: [ latency ]
  gamemode:
    aliases: [ gm ]
  gmc:
    aliases: [ gm1 ]
  gms:
    aliases: [ gm0 ]
  gmsp:
    aliases: [ gm3 ]
  gma:
    aliases: [ gm2 ]
  hub:
  heal:
  speed:
  tell:
    aliases: [ t, message, msg, whisper, w ]
  reply:
    aliases: [ r ]
  teleport:
    aliases: [ tp ]
  teleporthere:
    aliases: [ tphere ]
  skull:
    aliases: [ playerhead ]
  back:
  top:
  day:
    aliases: [ daytime ]
  night:
    aliases: [ nighttime ]
  lag:
    aliases: [ gc, memory, mem, performance ]
  item:
    aliases: [ giveitem, i ]
  staffchat:
    aliases: [ sc ]
  vanish:
    aliases: [ v ]
  copyinventory:
    aliases: [ ci ]
  crash:
  christmastree:
    aliases: [ xmastree ]
  armorstand:
    aliases: [ as ]
  identity:
    aliases: [ id ]
  itemstack:
    aliases: [ is ]
  whois:
    aliases: [ seen ]
  sun:
    aliases: [ sunny ]
  rain:
  knockback:
    aliases: [ kb ]
  feed:
  sudo:
  russianroulette:
  launch:
  freeze:
  unfreeze:
  sit:
    aliases: [ chair ]
  msgtoggle:
    aliases: [ togglemsg, ignore ]