name: pEssentials
version: ${project.version}
main: me.pafias.pessentials.pEssentials
softdepend: [ ProtocolLib, PlaceholderAPI ]
author: Pafias
description: Various useful features
api-version: 1.13
commands:
  entity:
    aliases: [ e ]
    permission: essentials.entity
  sound:
    aliases: [ snd ]
    permission: essentials.sound
  nightvision:
    aliases: [ nv ]
    permission: essentials.nightvision
  ping:
    aliases: [ latency ]
    permission: essentials.ping
  gamemode:
    aliases: [ gm ]
    permission: essentials.gamemode
  gmc:
    aliases: [ gm1 ]
    permission: essentials.gamemode
  gms:
    aliases: [ gm0 ]
    permission: essentials.gamemode
  gmsp:
    aliases: [ gm3 ]
    permission: essentials.gamemode
  gma:
    aliases: [ gm2 ]
    permission: essentials.gamemode
  hub:
  heal:
    permission: essentials.heal
  speed:
    permission: essentials.speed
  tell:
    aliases: [ t, message, msg, whisper, w ]
    permission: essentials.tell
  reply:
    aliases: [ r ]
    permission: essentials.reply
  teleport:
    aliases: [ tp ]
    permission: essentials.teleport
  teleporthere:
    aliases: [ tphere ]
    permission: essentials.teleporthere
  skull:
    aliases: [ playerhead ]
    permission: essentials.skull
  back:
    permission: essentials.back
  top:
    permission: essentials.top
  day:
    aliases: [ daytime ]
    permission: essentials.day
  night:
    aliases: [ nighttime ]
    permission: essentials.night
  lag:
    aliases: [ gc, memory, mem, performance ]
    permission: essentials.lag
  item:
    aliases: [ giveitem, i ]
  staffchat:
    aliases: [ sc ]
  vanish:
    aliases: [ v ]
  copyinventory:
    aliases: [ ci ]
  crash:
  christmastree:
    aliases: [ xmastree ]
  armorstand:
    aliases: [ as ]
  identity:
    aliases: [ id ]
  itemstack:
    aliases: [ is ]
  whois:
    aliases: [ seen ]
  sun:
    aliases: [ sunny ]
  rain:
  knockback:
    aliases: [ kb ]
  feed:
  sudo:
  russianroulette:
  launch:
  freeze:
  unfreeze:
  sit:
    aliases: [ chair ]
  msgtoggle:
    aliases: [ togglemsg, ignore ]
  invsee:
    aliases: [ inv ]
  discord:
    aliases: [ dc ]